### ISSUE TITLE
Compatibility with conduit-1.3.0

### ISSUE THREAD

**Issue by unode** [bigmac2k/lz4-conduit#2]
lz4-conduit isn't compatible with conduit-1.3.0 do you have any plans to implement the changes required?

Thanks

**Comment by scm2342** [comment]
Hi,
I'll try to have a look next weekend or in the evening. If you need it quicker than that, feel free to create a PR.

Regards

**Comment by scm2342** [comment]
Hi,
I just upgraded versions and ran tests, everything looks fine, feel free to check.

**Comment by unode** [comment]
On Linux things are indeed looking fine however on Windows I'm getting [some failures](https://ci.appveyor.com/project/luispedro/conduit-algorithms/build/1.0.7#L418).

Should I move Windows support discussion to another issue?

**Comment by scm2342** [comment]
Hi,
Yes please open another issue. I'll try to reproduce.

Sven

Am 26. März 2018 14:44:39 MESZ, schrieb Renato Alves <notifications@github.com>:
>On Linux things are indeed looking fine however on Windows I'm getting
>[some
>failures](https://ci.appveyor.com/project/luispedro/conduit-algorithms/build/1.0.7#L418).
>
>Should I move Windows support to another issue?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/bigmac2k/lz4-conduit/issues/2#issuecomment-376152707

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit WristMail gesendet.
